[package]
name = "dungeons"
version = "0.1.0"
authors = ["Patrick Minogue <patrick.minogue@gmail.com>"]
edition = "2018"

[dependencies]
amethyst = "0.12.0"

[features]
vulkan = ["amethyst/vulkan"]
metal = ["amethyst/metal"]